apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ex
  labels:
    app: fastapi-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-ex
  template:
    metadata:
      labels:
        app: fastapi-ex
    spec:
      containers:
        - name: fastapi-ex
          image: localhost:32000/fastapi-ex:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10            
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-ex
  labels:
    app: fastapi-ex
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: fastapi-ex

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ex
  labels:
    app: fastapi-ex
spec:
  tls:
    - hosts:
        - r.domain.com
      secretName: domain-tls
  rules:
    - host: r.domain.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: fastapi-ex
              port:
                number: 80
